create table person (
	id INT PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,	
	email VARCHAR(50) NOT NULL,
	gender VARCHAR(50) NOT NULL,
	address VARCHAR(50) NOT NULL,
	country VARCHAR(50) NOT NULL,
	dob DATE NOT NULL,
);
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (1, 'Erena', 'Stiant', 'estiant0@gov.uk', 'Male', '85 Porter Crossing', 'Colombia', '2021-05-18');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (2, 'Catharina', 'Oldfield-Cherry', 'coldfieldcherry1@sina.com.cn', 'Non-binary', '312 Brown Point', 'Cuba', '2020-09-02');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (3, 'Bird', 'Augar', 'baugar2@clickbank.net', 'Male', '44361 School Street', 'China', '2021-02-10');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (4, 'Kanya', 'Geake', 'kgeake3@statcounter.com', 'Agender', '2890 Melby Way', 'Myanmar', '2020-09-05');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (5, 'Chan', 'Tomasek', 'ctomasek4@theguardian.com', 'Female', '37 Center Way', 'Syria', '2021-01-25');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (6, 'Harald', 'Issakov', 'hissakov5@delicious.com', 'Male', '307 Mayer Crossing', 'China', '2021-05-29');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (7, 'Moria', 'McLay', 'mmclay6@addtoany.com', 'Agender', '9 Carpenter Park', 'Indonesia', '2021-01-06');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (8, 'Nathanael', 'Pellitt', 'npellitt7@prlog.org', 'Male', '3 Monterey Circle', 'Indonesia', '2021-06-02');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (9, 'Gus', 'Yeardsley', 'gyeardsley8@spotify.com', 'Genderfluid', '3056 Brown Plaza', 'Myanmar', '2021-07-22');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (10, 'Heinrik', 'Poyser', 'hpoyser9@jiathis.com', 'Bigender', '70830 Garrison Parkway', 'Japan', '2020-12-12');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (11, 'Marthena', 'Selland', 'msellanda@va.gov', 'Polygender', '8 East Park', 'Russia', '2021-02-16');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (12, 'Wynn', 'Ailmer', 'wailmerb@technorati.com', 'Genderqueer', '5350 Fremont Avenue', 'Philippines', '2021-01-15');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (13, 'Shermy', 'Berends', 'sberendsc@elegantthemes.com', 'Agender', '65750 Anderson Terrace', 'Philippines', '2021-07-30');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (14, 'Jo ann', 'Crump', 'jcrumpd@comcast.net', 'Agender', '83 Shoshone Trail', 'Mexico', '2020-10-23');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (15, 'Prinz', 'Jeff', 'pjeffe@reuters.com', 'Non-binary', '420 Farmco Center', 'Philippines', '2021-03-12');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (16, 'Patrizius', 'Julien', 'pjulienf@surveymonkey.com', 'Male', '8280 Porter Junction', 'Indonesia', '2020-10-16');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (17, 'Clarissa', 'Wolton', 'cwoltong@ucoz.ru', 'Male', '2 Vernon Point', 'China', '2021-05-04');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (18, 'Pierrette', 'Orrocks', 'porrocksh@salon.com', 'Genderqueer', '2580 Old Gate Court', 'Ukraine', '2020-12-12');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (19, 'Etan', 'Golightly', 'egolightlyi@sourceforge.net', 'Genderqueer', '951 Elka Park', 'Vietnam', '2020-12-11');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (20, 'Carmine', 'Desson', 'cdessonj@hugedomains.com', 'Polygender', '258 Cottonwood Road', 'Philippines', '2021-01-10');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (21, 'Emmalee', 'Dodle', 'edodlek@51.la', 'Agender', '36237 Dwight Hill', 'Russia', '2020-12-04');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (22, 'Kirstin', 'Forsyde', 'kforsydel@nydailynews.com', 'Male', '99407 Kings Crossing', 'Sweden', '2021-02-24');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (23, 'Ritchie', 'Clint', 'rclintm@joomla.org', 'Polygender', '895 Delaware Park', 'Canada', '2021-03-19');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (24, 'Corby', 'Bredgeland', 'cbredgelandn@springer.com', 'Polygender', '985 Northridge Crossing', 'Serbia', '2020-11-18');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (25, 'Joshua', 'Salman', 'jsalmano@msn.com', 'Genderfluid', '42 Coolidge Drive', 'Iran', '2020-09-01');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (26, 'Curry', 'Leap', 'cleapp@google.com.au', 'Agender', '1206 Butternut Plaza', 'Indonesia', '2020-10-08');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (27, 'Pierette', 'Springham', 'pspringhamq@yellowbook.com', 'Male', '8 Memorial Drive', 'Argentina', '2021-07-23');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (28, 'Harlene', 'Yuryaev', 'hyuryaevr@fc2.com', 'Agender', '2535 Memorial Alley', 'Sweden', '2020-10-29');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (29, 'Emanuele', 'Ovanesian', 'eovanesians@usgs.gov', 'Female', '03460 Esker Park', 'China', '2020-12-16');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (30, 'Candace', 'Skokoe', 'cskokoet@diigo.com', 'Female', '6 Northridge Alley', 'China', '2021-03-08');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (31, 'Elysia', 'Figliovanni', 'efigliovanniu@cdc.gov', 'Genderfluid', '55408 Ronald Regan Circle', 'Sweden', '2020-09-29');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (32, 'Archibald', 'Bertholin', 'abertholinv@usda.gov', 'Non-binary', '877 Sutherland Road', 'Russia', '2020-10-13');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (33, 'Latia', 'Whyman', 'lwhymanw@cpanel.net', 'Genderfluid', '47694 Starling Court', 'Indonesia', '2020-09-22');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (34, 'Ester', 'Bulgen', 'ebulgenx@wikimedia.org', 'Genderqueer', '6 Meadow Vale Alley', 'France', '2021-02-06');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (35, 'Jillayne', 'Halliwell', 'jhalliwelly@etsy.com', 'Genderqueer', '4644 Meadow Ridge Hill', 'China', '2021-03-31');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (36, 'Linda', 'Dondon', 'ldondonz@ox.ac.uk', 'Genderfluid', '3770 Sunfield Way', 'Jordan', '2021-03-02');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (37, 'Elvin', 'Umbert', 'eumbert10@wikipedia.org', 'Agender', '689 Cambridge Alley', 'Australia', '2021-02-16');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (38, 'Constancy', 'Neilson', 'cneilson11@wunderground.com', 'Male', '6169 Eagle Crest Place', 'Serbia', '2021-07-11');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (39, 'Raven', 'Arends', 'rarends12@kickstarter.com', 'Genderqueer', '33650 Maryland Road', 'Japan', '2021-01-13');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (40, 'Bowie', 'Chaster', 'bchaster13@infoseek.co.jp', 'Bigender', '0 Thierer Crossing', 'Norway', '2020-09-02');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (41, 'Joleen', 'Fidelus', 'jfidelus14@google.it', 'Male', '493 Roxbury Street', 'Tunisia', '2021-04-12');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (42, 'Tani', 'Scholcroft', 'tscholcroft15@nbcnews.com', 'Non-binary', '024 Corry Lane', 'Jordan', '2020-11-16');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (43, 'Brady', 'Niche', 'bniche16@bloglovin.com', 'Non-binary', '85 Larry Drive', 'Cuba', '2020-11-29');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (44, 'Butch', 'Tomaello', 'btomaello17@sogou.com', 'Polygender', '1 Mesta Plaza', 'Argentina', '2020-08-25');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (45, 'Karlotta', 'Clemow', 'kclemow18@google.pl', 'Male', '808 Everett Park', 'China', '2021-03-22');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (46, 'Saxon', 'Britten', 'sbritten19@ibm.com', 'Genderfluid', '74837 Sugar Road', 'China', '2020-09-09');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (47, 'Hyman', 'Zorzutti', 'hzorzutti1a@pinterest.com', 'Female', '75456 Spohn Way', 'Poland', '2021-05-06');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (48, 'Chelsey', 'Rappaport', 'crappaport1b@hibu.com', 'Genderqueer', '877 Dawn Terrace', 'Tajikistan', '2020-10-06');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (49, 'Layton', 'Finkle', 'lfinkle1c@harvard.edu', 'Genderfluid', '57 Rockefeller Drive', 'Poland', '2020-12-30');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (50, 'Jock', 'Learmont', 'jlearmont1d@imgur.com', 'Male', '76 Lotheville Point', 'France', '2020-09-19');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (51, 'Thorstein', 'Seeks', 'tseeks1e@mac.com', 'Male', '06232 Forest Run Trail', 'Indonesia', '2020-11-21');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (52, 'Hillyer', 'Tisun', 'htisun1f@so-net.ne.jp', 'Genderfluid', '3043 Huxley Drive', 'Vietnam', '2021-05-27');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (53, 'Leesa', 'Waddingham', 'lwaddingham1g@umich.edu', 'Female', '3593 Coolidge Road', 'China', '2021-06-05');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (54, 'Michal', 'Dinjes', 'mdinjes1h@earthlink.net', 'Genderqueer', '585 Hooker Pass', 'Argentina', '2020-12-11');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (55, 'Skipton', 'Jedrysik', 'sjedrysik1i@weather.com', 'Male', '1316 Petterle Place', 'Sweden', '2020-11-06');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (56, 'Darill', 'Bassindale', 'dbassindale1j@mayoclinic.com', 'Polygender', '9538 Sycamore Lane', 'Indonesia', '2020-11-14');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (57, 'Josselyn', 'Gianulli', 'jgianulli1k@xinhuanet.com', 'Male', '1041 Raven Junction', 'Indonesia', '2021-02-03');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (58, 'Lorna', 'Follacaro', 'lfollacaro1l@sohu.com', 'Female', '58 Mesta Plaza', 'Canada', '2021-06-13');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (59, 'Alexandre', 'Dome', 'adome1m@sfgate.com', 'Polygender', '29271 Blaine Street', 'Myanmar', '2021-07-25');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (60, 'Huey', 'Slaten', 'hslaten1n@springer.com', 'Agender', '1633 Buell Place', 'Poland', '2021-03-13');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (61, 'Anthiathia', 'Vizard', 'avizard1o@eepurl.com', 'Male', '093 Kim Junction', 'China', '2021-02-15');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (62, 'Brigida', 'Charette', 'bcharette1p@mac.com', 'Bigender', '853 Butterfield Street', 'China', '2021-02-02');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (63, 'Mallory', 'McKernon', 'mmckernon1q@last.fm', 'Male', '588 Maryland Drive', 'Malaysia', '2021-01-18');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (64, 'Fawne', 'Philipet', 'fphilipet1r@indiatimes.com', 'Female', '58268 Vera Trail', 'Russia', '2020-09-15');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (65, 'Jania', 'Rosendorf', 'jrosendorf1s@marriott.com', 'Polygender', '5 Monterey Road', 'Poland', '2021-04-12');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (66, 'Obie', 'Blincko', 'oblincko1t@google.com.br', 'Non-binary', '936 Montana Plaza', 'Guinea', '2021-03-20');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (67, 'Annemarie', 'Lumm', 'alumm1u@columbia.edu', 'Bigender', '07 Chive Hill', 'Estonia', '2020-09-14');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (68, 'Betsey', 'Brugger', 'bbrugger1v@flickr.com', 'Genderqueer', '2219 Morrow Hill', 'Argentina', '2021-05-25');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (69, 'Loydie', 'Blasgen', 'lblasgen1w@google.com.au', 'Bigender', '75 Springview Avenue', 'Russia', '2020-12-07');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (70, 'Lonnie', 'Fettiplace', 'lfettiplace1x@wikispaces.com', 'Genderfluid', '724 Trailsway Hill', 'Azerbaijan', '2020-09-11');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (71, 'Colman', 'Roswarn', 'croswarn1y@cnbc.com', 'Genderqueer', '83 Maple Hill', 'Portugal', '2020-08-28');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (72, 'Meghan', 'Scandrite', 'mscandrite1z@jimdo.com', 'Male', '240 Carioca Way', 'Philippines', '2021-04-20');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (73, 'Daffie', 'Goode', 'dgoode20@facebook.com', 'Bigender', '485 Nova Park', 'Italy', '2021-06-24');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (74, 'Jenilee', 'Howcroft', 'jhowcroft21@nbcnews.com', 'Polygender', '673 6th Park', 'Greece', '2020-12-30');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (75, 'Yettie', 'Nutbeem', 'ynutbeem22@dmoz.org', 'Genderqueer', '5207 Leroy Place', 'China', '2021-03-24');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (76, 'Arny', 'Jamme', 'ajamme23@mashable.com', 'Female', '2 Carey Hill', 'Poland', '2021-07-23');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (77, 'Josh', 'Du Pre', 'jdupre24@usgs.gov', 'Genderfluid', '3 Hudson Avenue', 'Mozambique', '2021-03-28');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (78, 'Alene', 'Donald', 'adonald25@nsw.gov.au', 'Agender', '4 Sunnyside Court', 'Ukraine', '2020-12-15');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (79, 'Rorke', 'Gianulli', 'rgianulli26@google.pl', 'Male', '32290 Mendota Street', 'Mexico', '2021-04-17');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (80, 'Tawnya', 'Kerrigan', 'tkerrigan27@google.co.uk', 'Non-binary', '4797 Melody Road', 'Pakistan', '2021-06-26');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (81, 'Wendall', 'Klimkov', 'wklimkov28@deliciousdays.com', 'Genderfluid', '73 Bultman Crossing', 'China', '2020-10-16');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (82, 'Cointon', 'Bottle', 'cbottle29@ft.com', 'Genderqueer', '8 Artisan Avenue', 'Palau', '2021-01-22');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (83, 'Daphne', 'Charley', 'dcharley2a@hp.com', 'Polygender', '78437 Melby Road', 'Ukraine', '2020-12-29');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (84, 'Sara', 'Cranny', 'scranny2b@state.tx.us', 'Polygender', '4 Orin Hill', 'China', '2020-12-05');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (85, 'Lorens', 'Troy', 'ltroy2c@rambler.ru', 'Agender', '77 Judy Circle', 'China', '2021-06-05');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (86, 'Terrel', 'Earie', 'tearie2d@behance.net', 'Female', '3 Thackeray Terrace', 'Russia', '2021-03-08');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (87, 'Alasdair', 'Liven', 'aliven2e@networkadvertising.org', 'Genderfluid', '096 Miller Parkway', 'Bosnia and Herzegovina', '2020-11-21');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (88, 'Zachary', 'Mineghelli', 'zmineghelli2f@prnewswire.com', 'Genderfluid', '18891 Express Alley', 'Macedonia', '2021-08-04');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (89, 'Jeralee', 'Benini', 'jbenini2g@foxnews.com', 'Polygender', '53 Stephen Street', 'Thailand', '2021-08-04');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (90, 'Andromache', 'Spragge', 'aspragge2h@theatlantic.com', 'Male', '8 Clove Junction', 'Madagascar', '2021-05-27');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (91, 'Cammie', 'Rubertis', 'crubertis2i@who.int', 'Female', '4823 Sloan Crossing', 'Poland', '2020-11-24');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (92, 'Bary', 'Beden', 'bbeden2j@netlog.com', 'Polygender', '49511 Veith Drive', 'New Zealand', '2020-11-28');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (93, 'Dom', 'Baptista', 'dbaptista2k@businessinsider.com', 'Polygender', '1054 Nevada Place', 'Jordan', '2020-12-17');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (94, 'Noellyn', 'Alvares', 'nalvares2l@simplemachines.org', 'Genderfluid', '9 Leroy Way', 'Brazil', '2020-12-13');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (95, 'Sephira', 'McCreagh', 'smccreagh2m@pcworld.com', 'Male', '08 Mayer Drive', 'Philippines', '2021-06-24');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (96, 'Waly', 'Kenzie', 'wkenzie2n@google.ca', 'Genderfluid', '091 Shelley Parkway', 'Venezuela', '2021-08-09');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (97, 'Joshuah', 'Normanville', 'jnormanville2o@mit.edu', 'Bigender', '03147 Annamark Court', 'Philippines', '2021-03-30');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (98, 'Alyosha', 'Brasier', 'abrasier2p@hp.com', 'Agender', '194 Jay Point', 'Russia', '2021-06-16');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (99, 'Igor', 'Hankey', 'ihankey2q@meetup.com', 'Non-binary', '1 John Wall Court', 'Germany', '2021-04-27');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (100, 'Jodie', 'Ganforth', 'jganforth2r@goo.gl', 'Polygender', '8 Old Gate Trail', 'Malawi', '2020-11-07');
insert into person (id, first_name, last_name, email, gender, address, country, dob) values (101, 'Joddie', 'Gforth', 'jganforth2r@goo.gl', 'Polygender', 'Gate Trail', 'Malawi', '2020-11-07');